version: "3.9"



services:
  library-api:
    build:
      context: ../server
      dockerfile: Dockerfile.dev
    image: dev-server
    container_name: dev-server
    volumes:
      - /app/node_modules
      - ../server:/app
    networks:
      - library-mern-api

  client:
    build:
      context: ../client
      dockerfile: Dockerfile.dev
    image: dev-client
    container_name: dev-client
    volumes:
      - ./app/node_modules
      - ../client:/app
    depends_on:
      - library-api
    networks:
      - library-mern-api

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile.dev
    image: dev-nginx
    container_name: dev-nginx
    ports:
      - "80:80"
    depends_on:
      - library-api
      - client
    networks:
      - library-mern-api

networks:
  library-mern-api:
    driver: bridge